server.port=8083
spring.main.banner-mode=off

logging.level.org.springframework=ERROR
logging.level.me.motemere.entrypoint=DEBUG

#logging.file.name=logs/entrypoint.log
#logging.logback.rollingpolicy.max-history=7
#logging.logback.rollingpolicy.max-file-size=10MB
#logging.logback.rollingpolicy.file-name-pattern=logs/archived/trypoint.%d{yyyy-MM-dd}.%i.log

spring.datasource.url = jdbc:mariadb://127.0.0.1:3306/testproject-db
spring.datasource.username=testproject
spring.datasource.password=testproject
spring.jpa.hibernate.ddl-auto=update

spring.application.name=entrypoint

#opentracing.jaeger.udp-sender.host=localhost
#opentracing.jaeger.udp-sender.port=6831
#opentracing.jaeger.log-spans=true

management.endpoints.web.exposure.include=health,info,prometheus
management.prometheus.metrics.export.enabled=true
management.tracing.sampling.probability=1.0
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces
management.otlp.metrics.export.enabled=false

websocket.uri=ws://localhost:8090/messages
